@extends('tienda::layouts.storefront')
@section('title', $page->title.' · '.$project->name)
@section('content')
@php $content=$page->content??[];$asset=fn($path)=>$path?(str_starts_with($path,'http')?$path:asset('storage/'.$path)):null; @endphp
<style>
.institutional-hero{display:grid;grid-template-columns:1.05fr .95fr;min-height:390px;background:#0f172a;color:#fff}.institutional-hero-copy{display:flex;flex-direction:column;justify-content:center;padding:clamp(38px,7vw,90px) max(28px,calc((100vw - 1180px)/2))}.institutional-hero h1{margin:0;font:800 clamp(38px,6vw,68px)/1.02 var(--store-font-title);letter-spacing:-.045em}.institutional-hero p{max-width:620px;margin:20px 0 0;color:rgba(255,255,255,.78);font-size:18px;line-height:1.7}.institutional-hero-media{min-height:360px;background:#e2e8f0 center/cover no-repeat}.institutional-sections{padding:64px 0;background:#f8fafc}.institutional-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.institutional-block{padding:30px;border:1px solid #e2e8f0;border-radius:12px;background:#fff}.institutional-block h2{margin:0 0 12px;color:#0f172a;font:750 25px/1.2 var(--store-font-title)}.institutional-block p{margin:0;color:#526176;line-height:1.75;white-space:pre-line}.institutional-values{display:grid;gap:8px;margin:0;padding:0;list-style:none}.institutional-values li{padding:10px 12px;border-left:3px solid var(--store-primary);background:#f8fafc}.institutional-cta{grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;gap:22px;background:#0f172a;color:#fff}.institutional-cta h2{color:#fff}@media(max-width:767px){.institutional-hero{grid-template-columns:1fr}.institutional-hero-copy{padding:46px 20px}.institutional-hero-media{min-height:260px}.institutional-sections{padding:38px 0}.institutional-grid{grid-template-columns:1fr}.institutional-block{padding:22px}.institutional-cta{align-items:flex-start;flex-direction:column}}
</style>
<style>.institutional-gallery{grid-column:1/-1;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.institutional-gallery img{width:100%;aspect-ratio:1/.68;object-fit:cover;border-radius:10px}@media(max-width:640px){.institutional-gallery{grid-template-columns:1fr}}</style>
<header class="institutional-hero"><div class="institutional-hero-copy"><h1>{{ $page->title }}</h1>@if(filled($content['body']??null))<p>{{ $content['body'] }}</p>@endif</div>@if($image=$asset($content['image']??null))<div class="institutional-hero-media" role="img" aria-label="{{ $page->title }}" style="background-image:url('{{ $image }}')"></div>@endif</header>
<section class="institutional-sections"><div class="store-container institutional-grid">
    @if(($content['show_history']??true)&&filled($content['history']??null))<article class="institutional-block"><h2>Nuestra historia</h2><p>{{ $content['history'] }}</p></article>@endif
    @if(($content['show_mission']??true)&&filled($content['mission']??null))<article class="institutional-block"><h2>Misión</h2><p>{{ $content['mission'] }}</p></article>@endif
    @if(($content['show_vision']??true)&&filled($content['vision']??null))<article class="institutional-block"><h2>Visión</h2><p>{{ $content['vision'] }}</p></article>@endif
    @if(($content['show_values']??true)&&filled($content['values']??null))<article class="institutional-block"><h2>Valores</h2><ul class="institutional-values">@foreach(preg_split('/\r\n|\r|\n/',$content['values']) as $value)@if(trim($value))<li>{{ trim($value) }}</li>@endif @endforeach</ul></article>@endif
    @if(($content['show_team']??true)&&filled($content['team']??null))<article class="institutional-block"><h2>Equipo</h2><p>{{ $content['team'] }}</p></article>@endif
    @if(($content['show_gallery']??true)&&!empty($content['gallery']))<div class="institutional-gallery">@foreach($content['gallery'] as $galleryImage)<img loading="lazy" src="{{ $asset($galleryImage) }}" alt="{{ $page->title }} — imagen {{ $loop->iteration }}">@endforeach</div>@endif
    @if(($content['show_cta']??true)&&filled($content['button_url']??null))<aside class="institutional-block institutional-cta"><div><h2>{{ $content['button_heading']??'¿Conversamos?' }}</h2><p>{{ $content['button_body']??'Estamos listos para ayudarte.' }}</p></div><a class="store-button" href="{{ $content['button_url'] }}">{{ $content['button_text']??'Contáctanos' }}</a></aside>@endif
</div></section>
@endsection
