@php $about=$pages->firstWhere('key','nosotros');$aboutContent=$about?->content??[];$contact=$pages->firstWhere('key','contacto');$contactContent=$contact?->content??[]; @endphp
<div class="grid gap-5 xl:grid-cols-2" id="institutional-pages">
  <form method="post" enctype="multipart/form-data" action="{{ route('settings.experience.page') }}" class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">@csrf<input type="hidden" name="key" value="nosotros"><h2 class="font-bold text-slate-900">Página Nosotros</h2><p class="mt-1 text-sm text-slate-500">Ocultar la opción del menú no elimina esta información.</p><div class="mt-4 grid gap-3 md:grid-cols-2"><label class="text-xs font-bold text-slate-600">Título<input name="title" required value="{{ $about?->title??'Nosotros' }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-xs font-bold text-slate-600">Imagen principal<input name="image" type="file" accept="image/*" class="mt-1 w-full rounded border-slate-300"></label></div><div class="mt-3 grid gap-3 md:grid-cols-2"><label class="text-xs font-bold text-slate-600">Etiqueta pequeña<input name="label" value="{{ $aboutContent['label']??'' }}" class="mt-1 w-full rounded border-slate-300" placeholder="Quiénes somos"></label><label class="text-xs font-bold text-slate-600">Título de la sección<input name="heading" value="{{ $aboutContent['heading']??'' }}" class="mt-1 w-full rounded border-slate-300" placeholder="Más de 14 años transformando hogares"></label></div><label class="mt-3 block text-xs font-bold text-slate-600">Presentación<textarea name="body" rows="3" class="mt-1 w-full rounded border-slate-300">{{ $aboutContent['body']??'' }}</textarea></label>
    @php $abIconOptions = ['target'=>'Diana','eye'=>'Ojo','star'=>'Estrella','heart'=>'Corazón','shield'=>'Escudo','award'=>'Medalla','users'=>'Personas','home'=>'Casa','truck'=>'Camión','clock'=>'Reloj','check'=>'Check','spark'=>'Destello']; @endphp
    {{-- Hero institucional --}}
    <div class="mt-3 rounded-lg bg-slate-50 p-3">
      <label class="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" name="hero_enabled" value="1" @checked($aboutContent['hero_enabled']??false)> Mostrar hero (banner grande debajo del menú)</label>
      <div class="mt-2 grid gap-2 md:grid-cols-2">
        <label class="text-xs font-bold text-slate-600">Imagen del hero (PC)@if(!empty($aboutContent['hero_image']))<img src="{{ asset('storage/'.$aboutContent['hero_image']) }}" alt="" class="mt-1 h-14 w-full rounded object-cover">@endif<input name="hero_image" type="file" accept="image/*" class="mt-1 w-full rounded border-slate-300"></label>
        <label class="text-xs font-bold text-slate-600">Imagen del hero (móvil, opcional)@if(!empty($aboutContent['hero_image_mobile']))<img src="{{ asset('storage/'.$aboutContent['hero_image_mobile']) }}" alt="" class="mt-1 h-14 w-full rounded object-cover">@endif<input name="hero_image_mobile" type="file" accept="image/*" class="mt-1 w-full rounded border-slate-300"></label>
        <input name="hero_title" value="{{ $aboutContent['hero_title']??'' }}" class="rounded border-slate-300" placeholder="Título del hero (ej. Nosotros)">
        <input name="hero_subtitle" value="{{ $aboutContent['hero_subtitle']??'' }}" class="rounded border-slate-300" placeholder="Frase (ej. Hacemos de tu hogar un lugar extraordinario)">
        <input name="hero_desc" value="{{ $aboutContent['hero_desc']??'' }}" class="rounded border-slate-300 md:col-span-2" placeholder="Descripción corta (opcional)">
        <label class="text-xs text-slate-600">Alineación<select name="hero_align" class="mt-1 w-full rounded border-slate-300"><option value="left" @selected(($aboutContent['hero_align']??'left')==='left')>Izquierda</option><option value="center" @selected(($aboutContent['hero_align']??'')==='center')>Centrado</option></select></label>
        <label class="text-xs text-slate-600">Altura<select name="hero_height" class="mt-1 w-full rounded border-slate-300"><option value="compact" @selected(($aboutContent['hero_height']??'')==='compact')>Compacta</option><option value="standard" @selected(($aboutContent['hero_height']??'standard')==='standard')>Estándar</option><option value="tall" @selected(($aboutContent['hero_height']??'')==='tall')>Alta</option></select></label>
        <label class="text-xs text-slate-600 md:col-span-2">Oscurecido de la imagen (overlay): <span class="font-bold">{{ $aboutContent['hero_overlay']??45 }}%</span><input type="range" name="hero_overlay" min="0" max="80" step="5" value="{{ $aboutContent['hero_overlay']??45 }}" class="mt-1 w-full" oninput="this.previousElementSibling.textContent=this.value+'%'"></label>
      </div>
    </div>
    @foreach(['history'=>'Historia','mission'=>'Misión','vision'=>'Visión','values'=>'Valores (uno por línea)','team'=>'Equipo'] as $key=>$label)<div class="mt-3"><label class="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" name="show_{{ $key }}" value="1" @checked($aboutContent['show_'.$key]??true)> Mostrar {{ strtolower($label) }}</label><textarea name="{{ $key }}" rows="3" class="mt-1 w-full rounded border-slate-300" placeholder="{{ $label }}">{{ $aboutContent[$key]??'' }}</textarea></div>@endforeach
    <div class="mt-3 grid gap-3 md:grid-cols-2"><label class="text-xs font-bold text-slate-600">Ícono de Misión<select name="mission_icon" class="mt-1 w-full rounded border-slate-300">@foreach($abIconOptions as $ik=>$il)<option value="{{ $ik }}" @selected(($aboutContent['mission_icon']??'target')===$ik)>{{ $il }}</option>@endforeach</select></label><label class="text-xs font-bold text-slate-600">Ícono de Visión<select name="vision_icon" class="mt-1 w-full rounded border-slate-300">@foreach($abIconOptions as $ik=>$il)<option value="{{ $ik }}" @selected(($aboutContent['vision_icon']??'eye')===$ik)>{{ $il }}</option>@endforeach</select></label></div>
    {{-- Diferenciales (banda de beneficios) --}}
    <div class="mt-3 rounded-lg bg-slate-50 p-3" x-data='{ diffs: @json(collect($aboutContent["differentials"] ?? [])->values()) }'>
      <label class="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" name="differentials_enabled" value="1" @checked($aboutContent['differentials_enabled']??true)> Mostrar banda de beneficios (diferenciales)</label>
      <input type="hidden" name="differentials" :value="JSON.stringify(diffs)">
      <template x-for="(d,i) in diffs" :key="i">
        <div class="mt-2 grid grid-cols-[110px_1fr_1fr_auto] items-center gap-2">
          <select class="rounded border-slate-300 text-xs" x-model="d.icon">@foreach($abIconOptions as $ik=>$il)<option value="{{ $ik }}">{{ $il }}</option>@endforeach</select>
          <input class="rounded border-slate-300 text-sm" placeholder="Título (ej. +14 años)" x-model="d.title">
          <input class="rounded border-slate-300 text-sm" placeholder="Descripción corta" x-model="d.text">
          <span class="flex gap-1 text-xs"><button type="button" class="px-1 text-slate-500" @click="if(i>0){[diffs[i-1],diffs[i]]=[diffs[i],diffs[i-1]]}" title="Subir">↑</button><button type="button" class="px-1 text-slate-500" @click="if(i<diffs.length-1){[diffs[i+1],diffs[i]]=[diffs[i],diffs[i+1]]}" title="Bajar">↓</button><button type="button" class="px-1 text-red-500" @click="diffs.splice(i,1)" title="Quitar">✕</button></span>
        </div>
      </template>
      <button type="button" class="mt-2 rounded border border-slate-300 px-3 py-1 text-xs font-semibold text-slate-600" @click="if(diffs.length<6)diffs.push({icon:'star',title:'',text:'',enabled:true})">+ Agregar beneficio (máx. 6)</button>
    </div>
    <div class="mt-3"><label class="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" name="show_gallery" value="1" @checked($aboutContent['show_gallery']??true)> Mostrar imágenes adicionales</label><input type="file" name="gallery_images[]" multiple accept="image/*" class="mt-1 w-full rounded border-slate-300"><small class="text-slate-400">Hasta 8 imágenes.</small></div>
    <div class="mt-3 rounded-lg bg-slate-50 p-3"><label class="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" name="show_cta" value="1" @checked($aboutContent['show_cta']??true)> Mostrar llamada a la acción</label><div class="mt-2 grid gap-2 md:grid-cols-2"><input name="button_heading" value="{{ $aboutContent['button_heading']??'' }}" class="rounded border-slate-300" placeholder="Título del bloque"><input name="button_text" value="{{ $aboutContent['button_text']??'' }}" class="rounded border-slate-300" placeholder="Texto del botón"><input name="button_body" value="{{ $aboutContent['button_body']??'' }}" class="rounded border-slate-300" placeholder="Texto breve"><input name="button_url" value="{{ $aboutContent['button_url']??'' }}" class="rounded border-slate-300" placeholder="/ruta o https://..."></div></div>
    <label class="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" name="is_enabled" value="1" @checked($about?->is_enabled??true)> Página publicada</label><button class="mt-4 min-h-11 rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white">Guardar Nosotros</button>
  </form>
  <form method="post" action="{{ route('settings.experience.page') }}" class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">@csrf<input type="hidden" name="key" value="contacto"><h2 class="font-bold text-slate-900">Página Contacto</h2><p class="mt-1 text-sm text-slate-500">Configura información, formulario, mapa y confirmación.</p><div class="mt-4 grid gap-3 md:grid-cols-2"><input name="title" required value="{{ $contact?->title??'Contacto' }}" class="rounded border-slate-300" placeholder="Título"><input name="email" type="email" value="{{ $contactContent['email']??'' }}" class="rounded border-slate-300" placeholder="Correo"><input name="phone" value="{{ $contactContent['phone']??'' }}" class="rounded border-slate-300" placeholder="Teléfono"><input name="whatsapp" value="{{ $contactContent['whatsapp']??'' }}" class="rounded border-slate-300" placeholder="WhatsApp"><input name="address" value="{{ $contactContent['address']??'' }}" class="rounded border-slate-300" placeholder="Dirección"><input name="hours" value="{{ $contactContent['hours']??'' }}" class="rounded border-slate-300" placeholder="Horarios"></div><textarea name="body" rows="3" class="mt-3 w-full rounded border-slate-300" placeholder="Texto introductorio">{{ $contactContent['body']??'' }}</textarea><input name="map_url" type="url" value="{{ $contactContent['map_url']??'' }}" class="mt-3 w-full rounded border-slate-300" placeholder="Enlace https:// del mapa"><div class="mt-3 grid gap-3 md:grid-cols-2"><input name="facebook_url" type="url" value="{{ $contactContent['facebook_url']??'' }}" class="rounded border-slate-300" placeholder="Facebook"><input name="instagram_url" type="url" value="{{ $contactContent['instagram_url']??'' }}" class="rounded border-slate-300" placeholder="Instagram"><input name="linkedin_url" type="url" value="{{ $contactContent['linkedin_url']??'' }}" class="rounded border-slate-300" placeholder="LinkedIn"><input name="tiktok_url" type="url" value="{{ $contactContent['tiktok_url']??'' }}" class="rounded border-slate-300" placeholder="TikTok"></div><div class="mt-3 flex flex-wrap gap-4 text-sm"><label><input type="checkbox" name="require_phone" value="1" @checked($contactContent['require_phone']??false)> Teléfono obligatorio</label><label><input type="checkbox" name="require_email" value="1" @checked($contactContent['require_email']??false)> Correo obligatorio</label></div><label class="mt-3 block text-xs font-bold text-slate-600">Mensaje de confirmación<textarea name="confirmation_message" rows="2" class="mt-1 w-full rounded border-slate-300">{{ $contactContent['confirmation_message']??'Recibimos tu mensaje. Te responderemos pronto.' }}</textarea></label><label class="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" name="is_enabled" value="1" @checked($contact?->is_enabled??true)> Página publicada</label><button class="mt-4 min-h-11 rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white">Guardar Contacto</button>
  </form>

  {{-- Páginas legales: si no las personalizas, la tienda muestra un texto base profesional. --}}
  @php $legalPages = ['privacidad' => 'Política de Privacidad', 'terminos' => 'Términos y Condiciones']; @endphp
  @foreach($legalPages as $lpKey => $lpLabel)
  @php $lp = $pages->firstWhere('key', $lpKey); $lpContent = $lp?->content ?? []; @endphp
  <form method="post" action="{{ route('settings.experience.page') }}" class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">@csrf<input type="hidden" name="key" value="{{ $lpKey }}">
    <h2 class="font-bold text-slate-900">{{ $lpLabel }}</h2>
    <p class="mt-1 text-sm text-slate-500">Visible en el pie de página de la tienda. Si la dejas vacía, se muestra un texto base con el nombre de tu negocio.</p>
    <label class="mt-4 block text-xs font-bold text-slate-600">Título<input name="title" required value="{{ $lp?->title ?? $lpLabel }}" class="mt-1 w-full rounded border-slate-300"></label>
    <label class="mt-3 block text-xs font-bold text-slate-600">Contenido<textarea name="body" rows="8" class="mt-1 w-full rounded border-slate-300" placeholder="Escribe aquí el texto completo. Los saltos de línea se respetan.">{{ $lpContent['body'] ?? '' }}</textarea></label>
    <label class="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" name="is_enabled" value="1" @checked($lp?->is_enabled ?? true)> Página publicada</label>
    <button class="mt-4 min-h-11 rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white">Guardar {{ $lpLabel }}</button>
  </form>
  @endforeach

  <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
    <h2 class="font-bold text-slate-900">Libro de Reclamaciones</h2>
    <p class="mt-1 text-sm text-slate-500">Activo automáticamente en tu tienda (Ley N.º 29571): los clientes lo encuentran en el pie de página. Cada registro genera un código y se envía copia a tu correo de contacto y al cliente.</p>
    <a class="mt-3 inline-flex min-h-11 items-center rounded-lg border border-indigo-200 bg-indigo-50 px-4 py-2 text-sm font-semibold text-indigo-700" href="{{ route('public.complaints.short', $project->slug) }}" target="_blank" rel="noopener">Ver mi Libro de Reclamaciones ↗</a>
  </div>
</div>
